import 'dart:io';
import 'dart:typed_data';

import 'package:photo_manager/photo_manager.dart';

/// {@template sf_media_asset}
/// Lightweight representation of a media item selected via `SFMediaPicker`.
///
/// This abstraction allows package consumers to work with selected assets
/// without depending directly on `photo_manager` types.
/// {@endtemplate}
class SfMediaAsset {
  /// {@macro sf_media_asset}
  const SfMediaAsset({
    required this.id,
    required this.type,
    required this.width,
    required this.height,
    required this.duration,
    this.title,
    this.createDateTime,
    this.modifiedDateTime,
  });

  /// Unique identifier provided by the underlying platform.
  final String id;

  /// Media classification.
  final SfMediaAssetType type;

  /// Pixel width of the original media.
  final int width;

  /// Pixel height of the original media.
  final int height;

  /// Duration of the asset. Non-zero for videos; zero for images.
  final Duration duration;

  /// Optional descriptive title.
  final String? title;

  /// Creation timestamp if available.
  final DateTime? createDateTime;

  /// Last modification timestamp if available.
  final DateTime? modifiedDateTime;

  /// Whether this asset represents a video.
  bool get isVideo => type == SfMediaAssetType.video;

  /// Whether this asset represents an image.
  bool get isImage => type == SfMediaAssetType.image;

  /// Loads the underlying file for this asset.
  ///
  /// Set [original] to `true` to request the original file where available.
  Future<File?> loadFile({bool original = false}) async {
    final AssetEntity? entity = await AssetEntity.fromId(id);
    if (entity == null) return null;
    return original ? entity.originFile : entity.file;
  }

  /// Loads thumbnail bytes generated by the platform media library.
  Future<Uint8List?> loadThumbnail({
    int width = 300,
    int height = 300,
    bool highQuality = true,
  }) async {
    final AssetEntity? entity = await AssetEntity.fromId(id);
    if (entity == null) return null;
    return entity.thumbnailDataWithSize(
      ThumbnailSize(width, height),
      quality: highQuality ? 100 : 70,
    );
  }

  /// Serialises this asset to a JSON-friendly map.
  Map<String, Object?> toJson() => <String, Object?>{
    'id': id,
    'type': type.name,
    'width': width,
    'height': height,
    'durationInMilliseconds': duration.inMilliseconds,
    'title': title,
    'createDateTime': createDateTime?.toIso8601String(),
    'modifiedDateTime': modifiedDateTime?.toIso8601String(),
  };

  /// Creates an asset instance from [json].
  factory SfMediaAsset.fromJson(Map<String, Object?> json) {
    final String rawType =
        (json['type'] as String?) ?? SfMediaAssetType.image.name;
    return SfMediaAsset(
      id: json['id']! as String,
      type: SfMediaAssetType.values.firstWhere(
        (SfMediaAssetType value) => value.name == rawType,
        orElse: () => SfMediaAssetType.image,
      ),
      width: (json['width'] as num?)?.toInt() ?? 0,
      height: (json['height'] as num?)?.toInt() ?? 0,
      duration: Duration(
        milliseconds: (json['durationInMilliseconds'] as num?)?.toInt() ?? 0,
      ),
      title: json['title'] as String?,
      createDateTime: _parseDate(json['createDateTime']),
      modifiedDateTime: _parseDate(json['modifiedDateTime']),
    );
  }

  static DateTime? _parseDate(Object? value) {
    if (value is String && value.isNotEmpty) {
      return DateTime.tryParse(value);
    }
    return null;
  }
}

/// Known media categories surfaced to package consumers.
enum SfMediaAssetType { image, video, audio, other }
